server:
  address: 127.0.0.1
  port: 9001
  #tomcat:
  #  accessLogEnabled: true
  session:
    timeout: 60000  # Session timeout in seconds.

logging:
  level:
    root: INFO
    me.ramswaroop: DEBUG
  file: /var/app/photo-finish/logs/dev.log
#    config:

spring:
  application:
    name: photo-finish
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/engymjpa
#    username: postgres
#    password: postgres
    #tomcat:
      #max-wait: 10000
      #max-active: 5
      #test-on-borrow: true
  #session:
    #store-type: jdbc
  #jdbc:
    #initialize-schema: embedded
    #table-name: session
  main:
    show_banner: false
  jackson:
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
  jmx:
    enabled: false
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate.jdbc.lob.non_contextual_creation: true
    generate-ddl: true
    #hibernate:
    # ddl-auto: create-drop
  flyway:
    enabled: true
    baseline-on-migrate: true
  redis:
    host: localhost
    port: 6379
    repo:
      api:
        user: userTest
        log: logTest
        photo:
          request: photoRequestTest
          image: photoImageTest
      telegram:
        user: telegramUserTest
        chat: telegramChatTest
        photo:
          image:
            notice: telegramPhotoImageNoticeTest
      facebook:
        user: facebookUserTest
        photo:
          image:
            notice: facebookPhotoImageNoticeTest

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full

#security:
#  basic:
#    enabled: false
#  user:
#    name: admin
#    password: nimda
#  oauth2:
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me

app:
  google_id: 564188442611-1qv3mvbqm3hi5r4c8krujb91pnsgn1o5.apps.googleusercontent.com

api:
  host: stage.finish.photo
  port: 80
  path: api/v1
  token: scW1pkc7j0ulWTebtbQq1SzCN7RWOSrtbb4iqGMK

# test
telegram:
  proxy:
    host: 67.205.162.60
    port: 1080
    user: triathlon
    password: triathlon
  bots:
    engym:
      name: EnGymTestBot
      token: 561609430:AAGIrvx8dRv19AJns9EhB2BSDsWb_PMgvSk
    entip:
      name: Entipbot
      token: 515897364:AAHGLvEHUCS1TbTGoH02vgBkUruGiHur4YQ
    photo-finish:
      name: Photofinishtestbot
      token: 766364951:AAFWDakmtxcUOHak5qJqeSHBQqw4ILtPkOo

# slack integrations
slackApi: https://slack.com/api
slackBotToken: <paste your slack bot token>
slashCommandToken: <paste your slash command token>
# replace the below url with your slack webhook url
slackIncomingWebhookUrl: https://slack.com

# fb bot
fbGraphApi: https://graph.facebook.com/v3.2
fbBotToken: fb_token_for_jbot
fbPageAccessToken: <paste your page access token>



---

# -------------------------------
# ---------- production ---------
# -------------------------------

spring:
  profiles: production
#  datasource:
#    url: jdbc:postgresql://localhost:5432/engymjpa
  redis:
    repo:
      api:
        user: user
        log: log
        photo:
          request: photoRequest
          image: photoImage
      telegram:
        user: telegramUser
        chat: telegramChat
        photo:
          image:
            notice: telegramPhotoImageNotice
      facebook:
        user: facebookUser
        photo:
          image:
            notice: facebookPhotoImageNotice

server:
  address: 127.0.0.1
  port: 9001

logging:
  file: /var/app/photo-finish/logs/prod.log


api:
  host: finish.photo
  port: 80
  path: api/v1
  token: scW1pkc7j0ulWTebtbQq1SzCN7RWOSrtbb4iqGMK

telegram:
#  proxy:
#    host: 185.247.140.57
#    port: 1080
#    user:
#    password:
  bots:
    engym:
      name: EnGymBot
      token: 441868585:AAFhRud_AaaV9dAr97MPUWtYIybX2Ph_ZGw
    entip:
      name: Entipbot
      token: 515897364:AAHGLvEHUCS1TbTGoH02vgBkUruGiHur4YQ
    photo-finish:
      name: Photofinishbot
      token: 203578507:AAEnhjxzCoJOn-bTVgPvB6YN9xIkYH-bLeg
